In [1]:
# 기본적인 라이브러리 import
import xlwings as xw
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from tqdm import tqdm
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')
plt.rcParams["font.family"] = 'NanumGothic'

In [4]:
data_df = pd.read_pickle("pkl_bonddata.pkl")
balance_df = pd.read_pickle("pkl_bondbalance.pkl")

In [6]:
balance_df

                     상장잔액증감
일자         종목명
2018-01-24 06-1     -700000
2019-01-16 06-1     -400000
2019-05-22 06-1    -1000000
2018-01-24 07-3    -1200000
2019-01-16 07-3    -1000000
...                     ...
2021-07-23 21-7    14900000
2021-08-24 21-7    91000000
2021-09-28 21-7   200000000
2021-10-07 21-10   80000000
2021-10-14 21-11   80000000

[1293 rows x 1 columns]

In [7]:
balance_df.isna().sum()

상장잔액증감    0
dtype: int64

In [9]:
data_df

,,민평금리,민평금리전일비,민평가격,듀레이션,전체순매수,외국인순매수,은행순매수,보험기금순매수,자산운용공모순매수,자산운용사모순매수,...,외국인대여,기타대여,증권차입,보험차입,투신차입,은행차입,연기금차입,외국인차입,기타차입,대차증감
일자,종목명,,,,,,,,,,,,,,,,,,,,,
2017-12-01,06-1,2.460,0.007,12578.30,6.7358,0,0,0,0,0,0,...,0,0,50000,0,9000,0,0,0,0,59000
2017-12-04,06-1,2.458,-0.002,12582.83,6.7278,28000000000,28000000000,0,0,0,0,...,0,0,0,0,1000,0,0,0,0,1000
2017-12-05,06-1,2.480,0.022,12564.78,6.7231,0,0,0,0,0,0,...,0,0,0,0,13000,0,0,0,0,13000
2017-12-06,06-1,2.448,-0.032,12593.27,6.7234,250000000,250000000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2017-12-07,06-1,2.460,0.012,12583.97,6.7195,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-08,21-9,2.335,0.028,9284.86,16.3482,27500000000,500000000,5000000000,22000000000,0,0,...,0,0,40000,0,0,0,0,0,0,27000
2021-10-12,21-9,2.370,0.035,9234.31,16.3226,27000000000,0,7000000000,20000000000,0,0,...,0,0,13000,0,0,0,0,0,0,13000
2021-10-13,21-9,2.347,-0.023,9269.64,16.3295,13000000000,0,1000000000,11000000000,1000000000,0,...,0,0,7000,0,0,0,0,0,0,7000
2021-10-12,21-10,1.877,0.000,9969.14,3.0655,-190000000000,0,-190000000000,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2021-10-13,21-10,1.885,0.008,9967.32,3.0626,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
df = data_df.join(balance_df, how='outer')

In [22]:
df.head()

                  민평금리  민평금리전일비      민평가격    듀레이션        전체순매수       외국인순매수  \
일자         종목명
2017-12-01 06-1  2.460    0.007  12578.30  6.7358          0.0          0.0
           07-3  2.485    0.008  12395.22  7.5001          0.0          0.0
           08-2  2.476    0.007  12851.82  8.1050 -230000000.0 -230000000.0
           08-5  1.780    0.000  10433.45  0.7518 -280000000.0 -280000000.0
           09-5  2.474    0.005  13391.25  9.1036          0.0          0.0

                 은행순매수  보험기금순매수  자산운용공모순매수  자산운용사모순매수  ...  기타대여     증권차입  \
일자         종목명                                         ...
2017-12-01 06-1    0.0      0.0        0.0        0.0  ...   0.0  50000.0
           07-3    0.0      0.0        0.0        0.0  ...   0.0      0.0
           08-2    0.0      0.0        0.0        0.0  ...   0.0      0.0
           08-5    0.0      0.0        0.0        0.0  ...   0.0  28600.0
           09-5    0.0      0.0        0.0        0.0  ...   0.0      0.0

                 보험차입     투신차입  은행차입  연기금차입  외국인차입   기타차입      대차증감  상장잔액증감
일자         종목명
2017-12-01 06-1   0.0   9000.0   0.0    0.0    0.0    0.0   59000.0     NaN
           07-3   0.0      0.0   0.0    0.0    0.0    0.0    -700.0     NaN
           08-2   0.0  76500.0   0.0    0.0    0.0  700.0   77200.0     NaN
           08-5   0.0      0.0   0.0    0.0    0.0    0.0 -146500.0     NaN
           09-5   0.0      0.0   0.0    0.0    0.0    0.0    -700.0     NaN

[5 rows x 35 columns]

In [57]:
# df.sort_index(level=1,inplace=True)
df.sort_index(inplace=True)
df

                   민평금리  민평금리전일비      민평가격    듀레이션        전체순매수       외국인순매수  \
일자         종목명
2017-12-01 06-1   2.460    0.007  12578.30  6.7358          0.0          0.0
           07-3   2.485    0.008  12395.22  7.5001          0.0          0.0
           08-2   2.476    0.007  12851.82  8.1050 -230000000.0 -230000000.0
           08-5   1.780    0.000  10433.45  0.7518 -280000000.0 -280000000.0
           09-5   2.474    0.005  13391.25  9.1036          0.0          0.0
...                 ...      ...       ...     ...          ...          ...
2021-10-14 13-8     NaN      NaN       NaN     NaN          NaN          NaN
           19-4     NaN      NaN       NaN     NaN          NaN          NaN
           20-4     NaN      NaN       NaN     NaN          NaN          NaN
           21-11    NaN      NaN       NaN     NaN          NaN          NaN
           21-8     NaN      NaN       NaN     NaN          NaN          NaN

                  은행순매수  보험기금순매수  자산운용공모순매수  자산운용사모순매수  ...  기타대여     증권차입  \
일자         종목명                                          ...
2017-12-01 06-1     0.0      0.0        0.0        0.0  ...   0.0  50000.0
           07-3     0.0      0.0        0.0        0.0  ...   0.0      0.0
           08-2     0.0      0.0        0.0        0.0  ...   0.0      0.0
           08-5     0.0      0.0        0.0        0.0  ...   0.0  28600.0
           09-5     0.0      0.0        0.0        0.0  ...   0.0      0.0
...                 ...      ...        ...        ...  ...   ...      ...
2021-10-14 13-8     NaN      NaN        NaN        NaN  ...   NaN      NaN
           19-4     NaN      NaN        NaN        NaN  ...   NaN      NaN
           20-4     NaN      NaN        NaN        NaN  ...   NaN      NaN
           21-11    NaN      NaN        NaN        NaN  ...   NaN      NaN
           21-8     NaN      NaN        NaN        NaN  ...   NaN      NaN

                  보험차입     투신차입  은행차입  연기금차입  외국인차입   기타차입      대차증감  \
일자         종목명
2017-12-01 06-1    0.0   9000.0   0.0    0.0    0.0    0.0   59000.0
           07-3    0.0      0.0   0.0    0.0    0.0    0.0    -700.0
           08-2    0.0  76500.0   0.0    0.0    0.0  700.0   77200.0
           08-5    0.0      0.0   0.0    0.0    0.0    0.0 -146500.0
           09-5    0.0      0.0   0.0    0.0    0.0    0.0    -700.0
...                ...      ...   ...    ...    ...    ...       ...
2021-10-14 13-8    NaN      NaN   NaN    NaN    NaN    NaN       NaN
           19-4    NaN      NaN   NaN    NaN    NaN    NaN       NaN
           20-4    NaN      NaN   NaN    NaN    NaN    NaN       NaN
           21-11   NaN      NaN   NaN    NaN    NaN    NaN       NaN
           21-8    NaN      NaN   NaN    NaN    NaN    NaN       NaN

                      상장잔액증감
일자         종목명
2017-12-01 06-1          NaN
           07-3          NaN
           08-2          NaN
           08-5          NaN
           09-5          NaN
...                      ...
2021-10-14 13-8   -9200000.0
           19-4  -22000000.0
           20-4   -7900000.0
           21-11  80000000.0
           21-8   80000000.0

[56565 rows x 35 columns]

In [66]:
df.loc['2021-10-13']

                  민평금리  민평금리전일비  민평가격  듀레이션  전체순매수  외국인순매수  은행순매수  보험기금순매수  \
일자         종목명
2021-10-14 11-7    NaN      NaN   NaN   NaN    NaN     NaN    NaN      NaN
           13-8    NaN      NaN   NaN   NaN    NaN     NaN    NaN      NaN
           19-4    NaN      NaN   NaN   NaN    NaN     NaN    NaN      NaN
           20-4    NaN      NaN   NaN   NaN    NaN     NaN    NaN      NaN
           21-11   NaN      NaN   NaN   NaN    NaN     NaN    NaN      NaN
           21-8    NaN      NaN   NaN   NaN    NaN     NaN    NaN      NaN

                  자산운용공모순매수  자산운용사모순매수  ...  증권차입  보험차입  투신차입  은행차입  연기금차입  \
일자         종목명                          ...
2021-10-14 11-7         NaN        NaN  ...   NaN   NaN   NaN   NaN    NaN
           13-8         NaN        NaN  ...   NaN   NaN   NaN   NaN    NaN
           19-4         NaN        NaN  ...   NaN   NaN   NaN   NaN    NaN
           20-4         NaN        NaN  ...   NaN   NaN   NaN   NaN    NaN
           21-11        NaN        NaN  ...   NaN   NaN   NaN   NaN    NaN
           21-8         NaN        NaN  ...   NaN   NaN   NaN   NaN    NaN

                  외국인차입  기타차입  대차증감      상장잔액증감  증권은행순매수
일자         종목명
2021-10-14 11-7     NaN   NaN   NaN  -1000000.0      NaN
           13-8     NaN   NaN   NaN  -9200000.0      NaN
           19-4     NaN   NaN   NaN -22000000.0      NaN
           20-4     NaN   NaN   NaN  -7900000.0      NaN
           21-11    NaN   NaN   NaN  80000000.0      NaN
           21-8     NaN   NaN   NaN  80000000.0      NaN

[6 rows x 36 columns]

In [69]:
df['증권은행순매수'] = df['은행순매수']-df['전체순매수']+df['상장잔액증감']*10000
df['증권은행순매수'].loc['2021-10-13'].isna()

일자          종목명
2021-10-13  06-1    True
            07-3    True
            08-2    True
            09-5    True
            10-7    True
                    ...
            21-5    True
            21-6    True
            21-7    True
            21-8    True
            21-9    True
Name: 증권은행순매수, Length: 68, dtype: bool

In [55]:
df.unstack().stack()

                   민평금리  민평금리전일비      민평가격    듀레이션        전체순매수       외국인순매수  \
일자         종목명
2017-12-01 06-1   2.460    0.007  12578.30  6.7358          0.0          0.0
           07-3   2.485    0.008  12395.22  7.5001          0.0          0.0
           08-2   2.476    0.007  12851.82  8.1050 -230000000.0 -230000000.0
           08-5   1.780    0.000  10433.45  0.7518 -280000000.0 -280000000.0
           09-5   2.474    0.005  13391.25  9.1036          0.0          0.0
...                 ...      ...       ...     ...          ...          ...
2021-10-14 13-8     NaN      NaN       NaN     NaN          NaN          NaN
           19-4     NaN      NaN       NaN     NaN          NaN          NaN
           20-4     NaN      NaN       NaN     NaN          NaN          NaN
           21-11    NaN      NaN       NaN     NaN          NaN          NaN
           21-8     NaN      NaN       NaN     NaN          NaN          NaN

                  은행순매수  보험기금순매수  자산운용공모순매수  자산운용사모순매수  ...  기타대여     증권차입  \
일자         종목명                                          ...
2017-12-01 06-1     0.0      0.0        0.0        0.0  ...   0.0  50000.0
           07-3     0.0      0.0        0.0        0.0  ...   0.0      0.0
           08-2     0.0      0.0        0.0        0.0  ...   0.0      0.0
           08-5     0.0      0.0        0.0        0.0  ...   0.0  28600.0
           09-5     0.0      0.0        0.0        0.0  ...   0.0      0.0
...                 ...      ...        ...        ...  ...   ...      ...
2021-10-14 13-8     NaN      NaN        NaN        NaN  ...   NaN      NaN
           19-4     NaN      NaN        NaN        NaN  ...   NaN      NaN
           20-4     NaN      NaN        NaN        NaN  ...   NaN      NaN
           21-11    NaN      NaN        NaN        NaN  ...   NaN      NaN
           21-8     NaN      NaN        NaN        NaN  ...   NaN      NaN

                  보험차입     투신차입  은행차입  연기금차입  외국인차입   기타차입      대차증감  \
일자         종목명
2017-12-01 06-1    0.0   9000.0   0.0    0.0    0.0    0.0   59000.0
           07-3    0.0      0.0   0.0    0.0    0.0    0.0    -700.0
           08-2    0.0  76500.0   0.0    0.0    0.0  700.0   77200.0
           08-5    0.0      0.0   0.0    0.0    0.0    0.0 -146500.0
           09-5    0.0      0.0   0.0    0.0    0.0    0.0    -700.0
...                ...      ...   ...    ...    ...    ...       ...
2021-10-14 13-8    NaN      NaN   NaN    NaN    NaN    NaN       NaN
           19-4    NaN      NaN   NaN    NaN    NaN    NaN       NaN
           20-4    NaN      NaN   NaN    NaN    NaN    NaN       NaN
           21-11   NaN      NaN   NaN    NaN    NaN    NaN       NaN
           21-8    NaN      NaN   NaN    NaN    NaN    NaN       NaN

                      상장잔액증감
일자         종목명
2017-12-01 06-1          NaN
           07-3          NaN
           08-2          NaN
           08-5          NaN
           09-5          NaN
...                      ...
2021-10-14 13-8   -9200000.0
           19-4  -22000000.0
           20-4   -7900000.0
           21-11  80000000.0
           21-8   80000000.0

[56565 rows x 35 columns]

In [53]:
df.loc[(,'06-1')]

SyntaxError: invalid syntax (<ipython-input-53-57c57a8680bc>, line 1)

In [41]:
df.loc[('2018-01-24','06-1'):('2018-01-30','06-1')]

UnsortedIndexError: 'Key length (2) was greater than MultiIndex lexsort depth (0)'

In [42]:
df

,,민평금리,민평금리전일비,민평가격,듀레이션,전체순매수,외국인순매수,은행순매수,보험기금순매수,자산운용공모순매수,자산운용사모순매수,...,기타대여,증권차입,보험차입,투신차입,은행차입,연기금차입,외국인차입,기타차입,대차증감,상장잔액증감
일자,종목명,,,,,,,,,,,,,,,,,,,,,
2017-12-01,06-1,2.460,0.007,12578.30,6.7358,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,...,0.0,50000.0,0.0,9000.0,0.0,0.0,0.0,0.0,59000.0,NaN
2017-12-04,06-1,2.458,-0.002,12582.83,6.7278,2.800000e+10,2.800000e+10,0.000000e+00,0.000000e+00,0.000000e+00,0.0,...,0.0,0.0,0.0,1000.0,0.0,0.0,0.0,0.0,1000.0,NaN
2017-12-05,06-1,2.480,0.022,12564.78,6.7231,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,...,0.0,0.0,0.0,13000.0,0.0,0.0,0.0,0.0,13000.0,NaN
2017-12-06,06-1,2.448,-0.032,12593.27,6.7234,2.500000e+08,2.500000e+08,0.000000e+00,0.000000e+00,0.000000e+00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2017-12-07,06-1,2.460,0.012,12583.97,6.7195,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1800.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-06,21-9,2.320,0.065,9306.48,16.3600,3.463000e+10,4.630000e+09,0.000000e+00,3.000000e+10,0.000000e+00,0.0,...,0.0,3000.0,0.0,0.0,0.0,0.0,0.0,0.0,3000.0,NaN
2021-10-07,21-9,2.307,-0.013,9326.88,16.3627,2.550000e+10,5.000000e+08,5.000000e+09,2.000000e+10,0.000000e+00,0.0,...,0.0,31000.0,0.0,0.0,0.0,0.0,0.0,3000.0,7000.0,NaN
2021-10-08,21-9,2.335,0.028,9284.86,16.3482,2.750000e+10,5.000000e+08,5.000000e+09,2.200000e+10,0.000000e+00,0.0,...,0.0,40000.0,0.0,0.0,0.0,0.0,0.0,0.0,27000.0,NaN
2021-10-12,21-9,2.370,0.035,9234.31,16.3226,2.700000e+10,0.000000e+00,7.000000e+09,2.000000e+10,0.000000e+00,0.0,...,0.0,13000.0,0.0,0.0,0.0,0.0,0.0,0.0,13000.0,NaN
2021-10-13,21-9,2.347,-0.023,9269.64,16.3295,1.300000e+10,0.000000e+00,1.000000e+09,1.100000e+10,1.000000e+09,0.0,...,0.0,7000.0,0.0,0.0,0.0,0.0,0.0,0.0,7000.0,NaN

In [25]:
df.loc[('2018-01-24','06-1')]

민평금리              2.6290
민평금리전일비           0.0030
민평가격          12485.2200
듀레이션              6.5735
전체순매수             0.0000
외국인순매수            0.0000
은행순매수             0.0000
보험기금순매수           0.0000
자산운용공모순매수         0.0000
자산운용사모순매수         0.0000
종금순매수             0.0000
정부순매수             0.0000
기타법인순매수           0.0000
개인순매수             0.0000
장내거래량             0.0000
장외거래량             0.0000
대차거래           9000.0000
대차상환              0.0000
대차잔량         333800.0000
증권대여              0.0000
보험대여              0.0000
투신대여              0.0000
은행대여           9000.0000
연기금대여             0.0000
외국인대여             0.0000
기타대여              0.0000
증권차입           9000.0000
보험차입              0.0000
투신차입              0.0000
은행차입              0.0000
연기금차입             0.0000
외국인차입             0.0000
기타차입              0.0000
대차증감           9000.0000
상장잔액증감      -700000.0000
Name: (2018-01-24 00:00:00, 06-1), dtype: float64

In [24]:
balance_df.head()

                  상장잔액증감
일자         종목명
2018-01-24 06-1  -700000
2019-01-16 06-1  -400000
2019-05-22 06-1 -1000000
2018-01-24 07-3 -1200000
2019-01-16 07-3 -1000000

In [11]:
data_df.shape

(56478, 34)

In [12]:
balance_df.shape

(1293, 1)